### ISSUE TITLE
Hello，guys.Maybe something is wrong .Look this

### ISSUE THREAD

**Issue by ByteYIFFF** [Shmeve/image-stitching#1]
![image](https://user-images.githubusercontent.com/38746426/50571017-f3bfac00-0dd9-11e9-98b2-11799fc1a756.png)

![1](https://user-images.githubusercontent.com/38746426/50571013-e73b5380-0dd9-11e9-994c-367e67b55c5b.PNG)

**Comment by Shmeve** [comment]
This was a class project that is no longer maintained. Alpha blending was never implemented and is not required to run the program.

**Comment by RikilD** [comment]
Very disappointed that this was closed and that you've censored us 👎
